<?php
/**
 * Created by PhpStorm.
 * User: gtguizhou
 * Date: 19-3-26
 * Time: 下午8:44
 */

namespace app\api\controller;


use app\common\controller\ApiBase;
use app\common\model\EmailTaskModel;
use app\common\model\FeedbackModel;
use my\Email;

class FeedbackController extends ApiBase
{
    protected $limitAction = ['except' => 'add'];

    protected function initialize()
    {
        $this->model = new FeedbackModel();
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function add()
    {
        parent::add(); // TODO: Change the autogenerated stub
        $content = input('content');
        $username = input('user_name');
        $html = "<table>
    <tr><th>意见反馈</th></tr>
    <tr><td>$username</td></tr>
    <tr><td>$content</td></tr>
</table>";
        $email = new Email('意见反馈',$html,config('email.to_feedback'));
        EmailTaskModel::create($email->getConfig()); //发送反馈邮件
        return success();
    }
}   