<?php
/**
 * Created by PhpStorm.
 * User: gtguizhou
 * Date: 19-3-26
 * Time: 下午8:44
 */

namespace app\api\controller;


use app\common\controller\ApiBase;
use app\common\key\RedisKey;
use app\common\model\HumanwallModel;
use my\RedisPool;

class HumanwallController extends ApiBase
{
    protected $limitAction = ['except' => 'read,indexAll,index,commentList,add'];

    protected function initialize()
    {
        $this->model = new HumanwallModel();
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function commentList(){
        $id = input('id');
        $redis = RedisPool::instance();
        $key = RedisKey::$HumanwallCommentList;
        $key = "$key:$id";
        // 获取所有弹幕
        $list = $redis->lGetRange($key,0,-1);
        // 清空弹幕
        $redis->lTrim($key,1,0);
        $redis->expire($key,config('humanwall.expire'));

        return success($list);
    }

}   