<?php
/**
 * Created by PhpStorm.
 * User: gtguizhou
 * Date: 19-3-26
 * Time: 下午8:44
 */

namespace app\api\controller;


use app\common\controller\ApiBase;
use app\common\model\LovewallModel;

class LovewallController extends ApiBase
{
    protected $limitAction = ['except' => 'readTemplate,indexAll,index,add,read,indexOfTemplate'];
    protected $addAfterResponseType = 'model';
    protected function initialize()
    {
        $this->model = new LovewallModel();
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function indexOfTemplate(){
        $templates = [
            'template1',
            'template2',
            'template3'
            ];
        $res = [];
        foreach ($templates as $template){
            array_push($res,$this->fetch($template,input()));
        }
        return  success($res);
    }

    /**
     * 读指定信件的模板
     */
    public function readTemplate(){
        $model = $this->model->findOrFail(input('id'));
        return $model['template'];
    }
}   