<?php
/**
 * Created by PhpStorm.
 * User: gtguizhou
 * Date: 19-3-26
 * Time: 下午8:44
 */

namespace app\api\controller;


use app\common\controller\ApiBase;
use app\common\model\MessageModel;

class MessageController extends ApiBase
{
    protected $limitAction = ['except' => 'index'];

    protected function initialize()
    {
        $this->model = new MessageModel();
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        $list = MessageModel::where(['user_id' => input('user_id')])->select();
        return success($list);
    }
}   