<?php
/**
 * Created by PhpStorm.
 * User: gtguizhou
 * Date: 19-3-26
 * Time: 下午8:44
 */

namespace app\api\controller;


use app\common\controller\ApiBase;
use app\common\model\QaModel;

class QaController extends ApiBase
{
    protected $limitAction = ['except' => 'indexAll,index,add,read'];

    protected function initialize()
    {
        $this->model = new QaModel();
        parent::initialize(); // TODO: Change the autogenerated stub
    }
}   