<?php
/**
 * Created by PhpStorm.
 * User: gtguizhou
 * Date: 19-3-26
 * Time: 下午8:44
 */

namespace app\api\controller;


use app\common\controller\ApiBase;
use app\common\model\SysconfigModel;
use think\db\exception\ModelNotFoundException;

class SysconfigController extends ApiBase
{
    protected $limitAction = ['except' => 'indexAll,index,update'];

    protected function initialize()
    {
        $this->model = new SysconfigModel();
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function indexAll(){
        $list = $this->model->select();
        $res = [];
        foreach ($list as $item){
            $res[$item['field']] = $item['value'];
        }

        return success($res);
    }

    public function update()
    {
        try{
            return parent::update(); // TODO: Change the autogenerated stub
        } catch (ModelNotFoundException $e){
            $this->addAfterResponseType = 'model';
            return $this->add();
        }
    }
}   