<?php
/**
 * Created by PhpStorm.
 * User: gtguizhou
 * Date: 19-3-26
 * Time: 下午8:44
 */

namespace app\api\controller;


use app\common\controller\ApiBase;
use app\common\exception\UnLoginException;
use app\common\model\MessageModel;
use app\common\model\RepairModel;
use app\common\model\UserModel;

class UserController extends ApiBase
{
    protected $limitAction = ['except' => 'info,usergroup'];

    protected function initialize()
    {
        $this->model = new UserModel();
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function info(){
        $user = null;
        try{
            $user = $this->user();
            // 报修情况
            $repair = RepairModel::where('user_id' , $user['id'])
                ->where('state' , '未处理')->find();
            // 用户是否有系统消息
            $message = MessageModel::where('user_id' , $user['id'])
                ->where('is_read',0)
                ->find();
            if ($message) {
                $message['is_read'] = 1;
                $message->save();
            }
            $user['repair'] = $repair;
            $user['message'] = $message;
        } catch (UnLoginException $e) {
        }
        return success($user);
    }

    /**
     * 读取多个数据
     * @return \think\response\Json
     */
    public function group(){
        $ids = input('ids');
        return success($this->model->scope('simpleinfo')->select($ids));
    }
}   