<?php
/**
 * Created by PhpStorm.
 * User: gtguizhou
 * Date: 19-3-26
 * Time: 下午8:44
 */

namespace app\api\controller;


use app\common\controller\ApiBase;
use app\common\model\ZfModel;
use zf\Main;

class ZfController extends ApiBase
{
    protected $limitAction = ['only' => 'indexAll,index'];
    /**
     * @var Main
     */
    private $main;
    protected function initialize()
    {
        $this->model = new ZfModel();
        $this->main = new Main();
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function login(){
        $user = $this->user();
        return $this->main->login($user['zf_act'],$user['zf_pwd'],input('code'));
    }

    public function checkCode(){
        return response($this->main->checkCode())->header('Content-Type','image/gif');
    }

    public function timetable(){
        $user = $this->user();
        $this->main->login($user['zf_act'],$user['zf_pwd'],input('code'));
        return success($this->main->timetable($user['zf_act']));
    }

    public function scoreReport(){
        $user = $this->user();
        $this->main->login($user['zf_act'],$user['zf_pwd'],input('code'));
        return success($this->main->scoreReport($user['zf_act']));
    }
}   